version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "22:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: webpack
    versions:
    - 2.7.0
    - 5.23.0
    - 5.24.1
    - 5.24.2
    - 5.24.3
    - 5.24.4
    - 5.25.0
    - 5.26.0
    - 5.26.3
    - 5.27.0
    - 5.27.2
    - 5.28.0
    - 5.30.0
    - 5.31.0
    - 5.31.2
    - 5.32.0
    - 5.33.2
    - 5.34.0
    - 5.35.0
    - 5.35.1
    - 5.36.0
  - dependency-name: npm
    versions:
    - 6.14.11
    - 7.10.0
    - 7.11.0
    - 7.5.2
    - 7.5.3
    - 7.5.4
    - 7.5.6
    - 7.6.0
    - 7.6.1
    - 7.6.2
    - 7.6.3
    - 7.7.0
    - 7.7.4
    - 7.7.5
    - 7.7.6
    - 7.8.0
    - 7.9.0
  - dependency-name: react-redux
    versions:
    - 7.2.1
    - 7.2.2
    - 7.2.3
  - dependency-name: react
    versions:
    - 16.14.0
    - 17.0.1
  - dependency-name: redux
    versions:
    - 4.0.5
  - dependency-name: ejs
    versions:
    - 3.1.5
